<a href="https://colab.research.google.com/github/theriyasharma24/LGMVIP-DataScience/blob/main/Iris_Flowers_Classification_ML_Project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Riya Sharma Data Science Intern at Lets Grow More Virtual Internship Program (October 2021 Batch)** 

**Task 1** :  Iris Flowers Classification ML Project

**Level** : Beginner

**Algorithm** : K Nearest Neighbour Classifier


**Importing Libraries :**
Importing libraries numpy and pandas.

In [ ]:
import pandas as pd
import numpy as np

**Exploring the Data :** We can load the dataset by using load_iris function.

In [ ]:
from sklearn.datasets import load_iris
iris_dataset = load_iris()

The iris object that is returned by  load_iris is similar to a dictionary.

In [ ]:
print("Keys of iris_dataset :\n{}".format(iris_dataset.keys()))

Keys of iris_dataset :
dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])


The value of DESCR is a short description of the dataset. It contains :

In [ ]:
val = iris_dataset['DESCR']
start_val = val[:200]
print(start_val + "\n...")

.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

    :Number of Instances: 150 (50 in each of three classes)
    :Number of Attributes: 4 numeric, predictive
...


The value of target_names is an array of strings ,containing the species of flower that we want to predict .

In [ ]:
print("Target names : {}".format(iris_dataset['target_names']))

Target names : ['setosa' 'versicolor' 'virginica']


The value of feature_name is an array of strings ,giving the description of each feature :

In [ ]:
print("Feature names : \n{}".format(iris_dataset['feature_names']))

Feature names : 
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


The data contains numeric measurements of sepal length , sepal width , petal length, and petal width in a NumPy array:

In [ ]:
print("Type of data : {}".format(type(iris_dataset['data'])))

Type of data : <class 'numpy.ndarray'>


The rows in this data array correspond to the flowers , while the columns represent the four measurements that were taken for each flower :

In [ ]:
print("Shape of data : {}".format(iris_dataset['data'].shape))

Shape of data : (150, 4)


Feature values for the first five samples:

In [ ]:
print("First five columns of data:\n{}".format(iris_dataset['data'][:5]))

First five columns of data:
[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


target array contains the species of each of the flowers that were meaasured , also as a NumPy array : 

In [ ]:
print("Type of target: {}".format(type(iris_dataset['target'])))

Type of target: <class 'numpy.ndarray'>


target is a one dimensional array , and on seeing the shape we can see that it contains oe entry per flower : 

In [ ]:
print("Shape of target : {}".format(iris_dataset['target'].shape))

Shape of target : (150,)


On seeing the target key and exploring the values we can easily see that the species are encoded as integers from 0 to 2 :

In [ ]:
print("Target:\n{}".format(iris_dataset['target']))


Target:
[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In this array , 0 means setosa , 1 means versicolor , and 2 means virginica.


**Measuring Success : Training and Testing Data :** 

Once a model has been built and trained we would like to test whether it actually works .

In [ ]:
from sklearn.model_selection import train_test_split
X_train , X_test , y_train , y_test = train_test_split(
    iris_dataset['data'],iris_dataset['target'],random_state=0)

Before making the split , the train_test_split function shuffles the dataset using a pseudorandom number generator.

In [ ]:
print("X_train shape:{}".format(X_train.shape))
print("y_train shape:{}".format(y_train.shape))
print("X_test shape:{}".format(X_test.shape))
print("y_test shape:{}".format(X_test.shape))

X_train shape:(112, 4)
y_train shape:(112,)
X_test shape:(38, 4)
y_test shape:(38, 4)


**Inspecting The Data :**

KNeighborsClassifier class is in the neighbors module.

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
knn=KNeighborsClassifier(n_neighbors=1)

The knn object encapsulates the algorithm that will be used to build the model from the training data, as well as the algorithm to make predictions on new data points.

In [ ]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

**Making Predictions :**

We can now make predictions on this model using new data for which we might not knw the correct labels .

In [ ]:
X_new = np.array([[5,2.9,1,0.2]])

print("X_new.shape :{}".format(X_new.shape))

X_new.shape :(1, 4)


Now, to make predictions , we call the predict method of the knn object : 

In [ ]:
prediction = knn.predict(X_new)

print("Prediction : {}".format(prediction))
print("Predicted target name : {}".format(
    iris_dataset['target_names'][prediction]))

Prediction : [0]
Predicted target name : ['setosa']



**Evaluating the Model**

We can make prediction for each iris in the test data and compare it against its label (the known species).

In [ ]:
y_pred = knn.predict(X_test)
print("Test set predictions :\n{}".format(y_pred))

Test set predictions :
[2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [ ]:
print("Test set score: {}".format(np.mean(y_pred == y_test)))

Test set score: 0.9736842105263158


The accuracy of our model is about 97 %.